name: Deploy to server via ftp
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v2
      - run: cd $GITHUB_WORKSPACE
      - run: ls
      - name: build application
        run: npm run build
        env:
          CI: false
      # - name: Upload ftp
      #   uses: genietim/ftp-action@releases/v4
      #   with:
      #     host: ${{ secrets.FTP_SERVER }}
      #     user: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     localDir: "build"
      #     remoteDir: "www"
